"""add_account_id_in_apps

Revision ID: 997733e43fb9
Revises: 380c6aa5a70d
Create Date: 2024-02-04 01:30:36.685726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '997733e43fb9'
down_revision = '380c6aa5a70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', postgresql.UUID(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
